version: '3.9'

services:
  hex_product_postgres:
    image: postgres:15
    container_name: hex_product_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: product
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - product-data:/var/lib/postgresql/data
    networks:
      - postgres

  hex_order_postgres:
    image: postgres:15
    container_name: hex_order_postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - order-data:/var/lib/postgresql/data
    networks:
      - postgres

  hex_pgadmin:
    container_name: hex_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - hex_product_postgres
      - hex_order_postgres

volumes:
  product-data:
  order-data:
  pgadmin:

networks:
  postgres:
    driver: bridge
