spring:
  application:
    name: order-service
  datasource:
    url: jdbc:postgresql://localhost:5433/order
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

rabbitmq:
  exchanges:
    internal: order.exchange
  queue:
    notification: notification.queue
  routing-keys:
    order-placed: order.placed
